---
title: "Data Types"
output: html_document
date: "2024-07-21"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
# Load the required library and dataset
library(dslabs)
data(murders)

# Examine the structure of the murders object
str(murders)

```
The state name, the abbreviation of the state name, the state's region, and the state's population and the total number of murders for 2010.

```{r}
# Extract the variable names (column names)
variable_names <- names(murders)

# Print the variable names
print(variable_names)
```

```{r}
# Access the population variable
p <- murders$population

# Determine the class of object `p`
class_p <- class(p)
print(class_p)

# Use the accessor to extract state abbreviations and assign it to `a`
a <- murders$abb

# Determine the class of `a`
class_a <- class(a)
print(class_a)
```

```{r}
# Extract the population variable using the dollar sign operator
p <- murders$population

# Extract the population variable using double square brackets
o <- murders[["population"]]

# Confirm if `o` and `p` are identical
identical_o_p <- identical(o, p)
print(identical_o_p)

# Use square brackets to extract `abb` from `murders` and assign it to `b`
b <- murders[["abb"]]

# Check if `a` and `b` are identical
identical_a_b <- identical(a, b)
print(identical_a_b)
```
```{r}
# Check the class of the region variable
region_class <- class(murders$region)
print(region_class)

# Use levels() to determine the unique regions included in the dataset
unique_regions <- levels(murders$region)
print(unique_regions)

# Determine the number of regions included in the dataset
num_regions <- length(unique_regions)
print(num_regions)
```
```{r}
# The "c" in `c()` is short for "concatenate," which is the action of connecting items into a chain
# The function `c()` connects all of the strings within it into a single vector, which we can assign to `x`
x <- c("a", "a", "b", "b", "b", "c")
# Here is an example of what the table function does
table(x)

# Write one line of code to show the number of states per region
table(murders$region)

```


